version: "3.9"
services:
    traefik:
        image: traefik:2.4
        command:
            --providers.docker=true
            --providers.docker.exposedByDefault=false
            --entryPoints.http.address=:80
        ports:
            - "80:80"
        networks:
            - traefik-public
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
        labels:
            - traefik.enable=true
            - traefik.docker.network=traefik-public

    api:
        build:
            context: api/docker
            dockerfile: development/nginx/Dockerfile
        volumes:
            - ./api:/app
        networks:
            - traefik-public
            - default
        labels:
            - traefik.enable=true
            - traefik.docker.network=traefik-public
            - traefik.http.routers.api.rule=Host(`api.localhost`)
            - traefik.http.routers.api.entryPoints=http
            - traefik.http.services.api.loadBalancer.server.port=80

    api-php-fpm:
        build:
            context: api/docker
            dockerfile: development/php-fpm/Dockerfile
        environment:
            APP_ENV: dev
            APP_DEBUG: 1
            PHP_IDE_CONFIG: serverName=API
            DB_HOST: api-postgres
            DB_USER: app
            DB_PASSWORD_FILE: /run/secrets/api_db_password
            DB_NAME: app
        volumes:
            - ./api:/app

    api-php-cli:
        build:
            context: api/docker
            dockerfile: development/php-cli/Dockerfile
            target: base_image
        environment:
            APP_ENV: dev
            APP_DEBUG: 1
            PHP_IDE_CONFIG: serverName=API
            DB_HOST: api-postgres
            DB_USER: app
            DB_PASSWORD_FILE: /run/secrets/api_db_password
            DB_NAME: app
        volumes:
            - ./api:/app

    api-postgres:
        image: postgres:13.3-alpine
        environment:
            POSTGRES_USER: app
            POSTGRES_PASSWORD_FILE: /run/secrets/api_db_password
            POSTGRES_DB: app
        secrets:
            - api_db_password
        volumes:
            - api-postgres:/var/lib/postgresql/data
        ports:
            - "5432:5432"

    frontend:
        build:
            context: frontend/docker/development/nginx
        networks:
            - traefik-public
            - default
        labels:
            - traefik.enable=true
            - traefik.docker.network=traefik-public
            - traefik.http.routers.frontend.rule=Host(`localhost`) || Host(`www.localhost`)
            - traefik.http.routers.frontend.entryPoints=http
            - traefik.http.services.frontend.loadBalancer.server.port=80
            - traefik.http.middlewares.frontend-redirect.redirectRegex.regex=^(https?://)www.localhost/(.*)$$
            - traefik.http.middlewares.frontend-redirect.redirectRegex.replacement=$${1}localhost/$${2}
            - traefik.http.middlewares.frontend-redirect.redirectRegex.permanent=true
            - traefik.http.routers.frontend.middlewares=frontend-redirect

    frontend-node:
        build:
            context: frontend/docker/development/node
        volumes:
            - ./frontend:/app
        command: sh -c "until [ -f .ready ] ; do sleep 1 ; done && yarn serve -- --port 3000"
        tty: true

    frontend-node-cli:
        build:
            context: frontend/docker/development/node
        volumes:
            - ./frontend:/app

    api-postgres-backup:
        build:
            context: ./api/docker/common
            dockerfile: postgres-backup/Dockerfile
        environment:
            BACKUP_NAME: to-do_api-postgres
            POSTGRES_HOST: api-postgres
            POSTGRES_DB: app
            POSTGRES_USERNAME: app
            POSTGRES_PASSWORD_FILE: /run/secrets/api_db_password
            AWS_ACCESS_KEY_ID: storage_app
            AWS_SECRET_ACCESS_KEY_FILE: /run/secrets/backup_aws_secret_access_key
            AWS_DEFAULT_REGION: region
            S3_ENDPOINT: http://backup-storage:9000
            S3_BUCKET: backup
        secrets:
            - api_db_password
            - backup_aws_secret_access_key
        command: sh -c 'wait-for-it api-postgres:5432 -t 20 && backup'

    backup-storage:
        image: minio/minio
        environment:
            MINIO_ROOT_USER: storage_app
            MINIO_ROOT_PASSWORD_FILE: /run/secrets/backup_aws_secret_access_key
        secrets:
            - backup_aws_secret_access_key
        volumes:
            - backup-storage:/data
        entrypoint: sh -c 'mkdir -p /data/backup && docker-entrypoint.sh minio server /data --console-address ":80"'
        networks:
            - traefik-public
            - default
        labels:
            - traefik.enable=true
            - traefik.docker.network=traefik-public
            - traefik.http.routers.backup-storage.rule=Host(`backup-storage.localhost`)
            - traefik.http.routers.backup-storage.entryPoints=http
            - traefik.http.services.backup-storage.loadBalancer.server.port=80

secrets:
    api_db_password:
        file: ./docker/development/secrets/api_db_password
    backup_aws_secret_access_key:
        file: ./docker/development/secrets/backup_aws_secret_access_key

volumes:
    api-postgres:
    backup-storage:

networks:
    traefik-public:
        name: traefik-public
