name: Pipeline

on: push

env:
  REGISTRY: ghcr.io/impfou/to-do
  REGISTRY_HOST: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker:stable
      volumes:
        # Mount the docker sock for host's docker engine to be usable inside container
        - /var/run/docker.sock:/var/run/docker.sock

    steps:
      -   uses: actions/checkout@v2

      -   name: Cache API composer
          uses: actions/cache@v2
          with:
            path: api/vendor
            key: api-composer-${{ hashFiles('api/composer.lock') }}

      -   name: Cache frontend yarn
          uses: actions/cache@v2
          with:
            path: frontend/node_modules
            key: frontend-yarn-${{ hashFiles('frontend/yarn.lock') }}

      -   name: Docker login
          uses: azure/docker-login@v1
          with:
            login-server: ${{ env.REGISTRY_HOST }}
            username: impfou
            password: ${{ github.token }}

      -   name: Dev Init
          run: make init

      -   name: Push dev cache images
          run: make push-dev-cache

      -   name: Analyze API
          run: make api-analyze

      -   name: Test API
          id: api-test
          run: make api-test

      -   name: Archive tests output
          uses: actions/upload-artifact@v1
          with:
            name: test-output
            path: api/var/log
          if: ${{ always() && steps.api-test.outcome == 'failure' }}

      -   name: Dev Down
          run: make docker-down-clear